const {chromium}=require('playwright');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:"chrome"});
 const page=await browser.newPage({viewport:{width:1100,height:780}});
 await page.route('https://example.com/email-assets/**', route => route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400"><rect width="600" height="400" fill="pink"/></svg>'}));
 await page.route('https://fonts.googleapis.com/**', route => route.abort());
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'ui.html')).href);
 await page.waitForTimeout(4500);
 await page.locator('[data-key=brand]').fill('Deneme Marka');
 await page.locator('[data-key=cta]').fill('Birlikte Başlayalım');
 await page.waitForTimeout(500);
 assert((await page.frameLocator('#preview').locator('body').innerText()).includes('Birlikte Başlayalım'));
 await page.locator('[data-template=website]').click();
 await page.locator('[data-key=brand]').fill('Web Markası');
 await page.locator('[data-key=cta]').fill('Web Görüşmesi');
 await page.waitForTimeout(400);
 assert((await page.frameLocator('#preview').locator('body').innerText()).includes('Web Görüşmesi'));
 await page.locator('[data-tab=images]').click();
 assert(await page.locator('.image-card').count()>4);
 await page.locator('[data-tab=drafts]').click();
 await page.getByRole('button',{name:'Yeni taslak olarak kaydet'}).click();
 assert(await page.locator('.draft').count()>=2);
 await page.locator('[data-tab=content]').click();
 await page.locator('[data-key=ctaUrl]').fill('javascript:alert(1)');
 await page.locator('#download').click();
 assert((await page.locator('#message').innerText()).includes('HTTPS'));
 await page.locator('[data-key=ctaUrl]').fill('https://example.com');
 const dl=page.waitForEvent('download');await page.locator('#download').click();
 const download=await dl;assert(download.suggestedFilename().endsWith('.html'));
 await download.saveAs(path.join(__dirname,'test-export.html'));
 await page.locator('[data-template=creative]').click();
 await page.waitForTimeout(1000);
 await page.evaluate(()=>{
  window.addEventListener('message',e=>{if(e.data?.pluginMessage?.type==='render')window.testScene=e.data.pluginMessage.scene;});
  window.postMessage({pluginMessage:{type:'init',drafts:[]}},'*');
 });
 await page.locator('#figma').click();
 await page.waitForFunction(()=>!!window.testScene);
 const scene=await page.evaluate(()=>window.testScene);
 assert(scene.nodes.some(n=>n.type==='image'));
 assert(scene.nodes.some(n=>n.type==='text'&&n.text.includes('HELLO')));
 assert.equal(scene.width,600);
 require('node:fs').writeFileSync(path.join(__dirname,'test-scene.json'),JSON.stringify(scene));
 await page.evaluate(()=>window.postMessage({pluginMessage:{type:'rendered',warnings:[]}},'*'));
 await page.evaluate(()=>{document.querySelector('aside').scrollTop=0;document.querySelector('.canvas').scrollTop=0;window.scrollTo(0,0);});
 const buttonBox=await page.locator('#download').boundingBox();
 assert(buttonBox.y>=0&&buttonBox.y+buttonBox.height<=780);
 await page.screenshot({path:path.join(__dirname,'preview.png')});
 assert.deepEqual(errors,[]);
 console.log('Browser: template switching, live editing, drafts, export validation/download passed.');
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});

